[package]
name = "postgres-extension-macro"
version = "0.1.0"
authors = ["Jeff Davis <jdavis@postgresql.org>"]
edition = "2018"
license = "PostgreSQL OR MIT"
description = "macro crate for postgres-extension"

[lib]
proc-macro = true
