[package]
name = "postgres-sys"
version = "0.1.0"
authors = ["Jelte Fennema <github-tech@jeltef.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.52"
